### ISSUE TITLE
Main build fails

### ISSUE THREAD

**Issue by lgiordani** [pelican-plugins/series#37]
Unfortunately the merge of PR #35 fails and I have no clue how to fix it as there is a lot of automation going on. Can you please help? The build works locally, I'm actually using it for my blog.

Thanks.

**Comment by justinmayer** [comment]
Hey Leonardo. Hope you are doing well. When you say (1) there is a lot of automation going on, and (2) you don't know how to fix it, it's not really clear what you mean on either count. What have you tried? Did you look at the output in GitHub's Actions tab? Perhaps you could elaborate?

**Comment by lgiordani** [comment]
Hey @justinmayer sorry for the vague description above. Let me elaborate:

1) The failure is: `Package docutils (0.21.post1) not found.` but I@m not familiar with poetry and I don't know why it's having issues with that package and how to fix it.
2) The error happens after the merge. This means that the branch `main` contains the code but the code cannot be deployed. However, there is a bot publishing packages here, and the branch `main` contains the file `RELEASE.md`. Provided I have a solution that fixes the tests, shall I create a PR? Commit directly in `main`?

Hope this clarifies! Thanks

**Comment by justinmayer** [comment]
What I did:

1. Look at Action tab logs: https://github.com/pelican-plugins/series/actions/runs/8870375141/job/24352099807#step:7:17

2. Note the error displayed: "Package docutils (0.21.post1) not found"

3. Search Internet for: "Package docutils (0.21.post1) not found"

4. See that first few links in search results indicate this is a known problem:

- https://github.com/pypi/warehouse/issues/15749
- https://github.com/python-poetry/poetry/issues/9293

5. Look at commits linked at bottom of above threads to see how other folks have fixed this problem: `docutils = "!=0.21.post1"`

**Comment by lgiordani** [comment]
Oh well, thanks! That was fast and answered my questions.
