### ISSUE TITLE
Possible inconsistency between plugin code and code example

### ISSUE THREAD

**Issue by tooh** [pelican-plugins/series#40]
Readme contains below example.

```
{% for series_name, series_articles in series.items() %}
{% set article = series_articles[0] %}
<article class="card">
	<a href="{{ article.url }}" class="image">
		<img src="/images/{{ article.image }}.jpg" alt="{{ article.image }}" />
	</a>
	<div class="card-body">
    	<a href="{{ article.url }}"><h3 class="card-title">{{ series_name }}</h3></a>
     	<ul class="actions">
     		<li><a href="{{ article.url }}" class="button">Start</a></li>
     	</ul>
	</div>
</article>
{% endfor %}
```

This produces no output on my blog.

When I change this line

` {% for series_name, series_articles in series.items() %}`

To 

`{% for series_name, series_articles in article_series.items() %}`

This produces output.

In the doc is mentioned a change in this area.

**Comment by justinmayer** [comment]
Thank you for reporting this, Peter. I updated the documentation via: 1f3eba3

**Comment by lgiordani** [comment]
Thanks both!
